apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      service: reverseproxy
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
        - name: reverseproxy
          image: abdullahfdarwish/udagram-reverseproxy:v1
          imagePullPolicy: Always
          ports:
          - containerPort: 80
            protocol: TCP
      restartPolicy: Always
